version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql-petshop
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: usuario
      MYSQL_PASSWORD: ${DB_PASSWORD_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: back-end-petshop
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: front-end-petshop
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mysql-data:
