FROM node:22

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm prune --production

# Copia o script e garante permissão
COPY wait-for.sh /app/wait-for.sh
RUN chmod +x /app/wait-for.sh

EXPOSE 5000

# 🛠️ Use 'bash' no CMD para suportar /dev/tcp
CMD ["bash", "-c", "./wait-for.sh mysql 3306 npm start"]